name: Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install bats-core
      run: |
        sudo apt-get update
        sudo apt-get install -y bats
    
    - name: Make test script executable
      run: chmod +x run_tests.sh
    
    - name: Run unit tests
      run: ./run_tests.sh
    
    - name: Check script syntax
      run: bash -n gshot-copy
    
    - name: Run ShellCheck
      run: shellcheck gshot-copy run_tests.sh tests/test_helper.bash